### ISSUE TITLE
Downloading dependency too slow

### ISSUE THREAD

**Issue by lyfer233** [shebinleo/pdf2html#15]
Downloading dependency "pdfbox-app-2.0.16.jar"and "tika-app-1.22" is too slow. 
In spite of  I try taking these .jar file into "_node_modules\pdf2html\vendor_ ", but it always automatic download.
I don't know how to solve this problem~

**Comment by thuccoi** [comment]
YES. Me too in this case. Pleas help me!!
<img width="313" alt="Screen Shot 2021-11-22 at 09 26 56" src="https://user-images.githubusercontent.com/10832811/142792053-b872478e-3a63-40ca-89ad-6356214b87f3.png">
!!

**Comment by shebinleo** [comment]
You can manually download pdfbox-app-2.0.16.jar and tika-app-1.22.jar files and place them in the vendor directory. The post-install script will skip the dependency downloads if the file exists.

```
http://archive.apache.org/dist/pdfbox/2.0.16/pdfbox-app-2.0.16.jar
http://archive.apache.org/dist/tika/tika-app-1.22.jar
```
