### ISSUE TITLE
Error: Failed downloading dependency

### ISSUE THREAD

**Issue by jonmadison** [shebinleo/pdf2html#20]
while attempting to npm install pdf2html, i'm getting:

```Error: Failed downloading dependency tika-app-2.1.0.jar.```

and/or

```Error: Failed downloading dependency pdfbox-app-2.0.24.jar.```

Depending on the project.  I'm grasping at straws here and wondering if it has to do with the recent log4j issues, but figured i'd at least leave the report before diving deeper.

Update: indeed pdfbox-app-2.0.24.jar is no longer available [on the site](https://pdfbox.apache.org/download.html), but 2.0.25.jar is

**Comment by marcosmoski** [comment]
Same here, the pdfbox-app-2.0.24 is available only on /dist folder. 
http://archive.apache.org/dist/pdfbox/

Same for de tika dependency.
http://archive.apache.org/dist/tika/

Can you check pls and update ? I need this to compile and build my app hahaha.

Many thanks !

**Comment by jonmadison** [comment]
I've updated [in my fork](https://github.com/jonmadison/pdf2html?organization=jonmadison&organization=jonmadison), will issue a pull request soon as i can.

**Comment by marcosmoski** [comment]
> I've updated [in my fork](https://github.com/jonmadison/pdf2html?organization=jonmadison&organization=jonmadison), will issue a pull request soon as i can.
> 
> in the meantime, try replacing your dependency to
> 
> ```
> "pdf2html": "https://github.com/jonmadison/pdf2html.git",
> ```

Thanks man !
