### ISSUE TITLE
Update tika from 2.2.1 to 2.3.0 to be able to install

### ISSUE THREAD

**Issue by jacksonwillrich** [shebinleo/pdf2html#25]
Hello.
A new Tika version was released and the endpoint 'https://dlcdn.apache.org/tika/2.2.1/tika-app-2.2.1.jar' that the postinstall tries to access now returns a 404 error, because of this it is not being possible to install the package. Please update the dependency to use the new version 2.3.0.

**Comment by shebinleo** [comment]
Thank you for the PR
