### ISSUE TITLE
How to keep the PDF text formatting?

### ISSUE THREAD

**Issue by dev1609** [shebinleo/pdf2html#27]
Hello, I do I make sure that the text formatting, such as bold, italic, bigger font size, such formatting are preserved when I am converting the file to html.

**Comment by shebinleo** [comment]
@dev1609 this library is just a wrapper for Apache Tika with some additional helper methods. Usually, most of the formatting is preserved when converted to HTML.

**Comment by dev1609** [comment]
> @dev1609 this library is just a wrapper for Apache Tika with some additional helper methods. Usually, most of the formatting is preserved when converted to HTML.

Okay, I used the library and tried converting fews PDFs but the bold text wasn't retained, everything was plain text.
