### ISSUE TITLE
Dependency installation error: tika-app-2.3.0.jar (page not found)

### ISSUE THREAD

**Issue by gustavoaraujofe** [shebinleo/pdf2html#36]
The installation url for tika-app-2.3.0.jar does not exist, causing an error in the package installation.
https://github.com/shebinleo/pdf2html/blob/9dda2d69a679569469ff7a7c1a0b7a770358aeac/postinstall.js#L7

**Comment by chengjianhua** [comment]
+1 I encountered the same issue.

<img width="415" alt="image" src="https://user-images.githubusercontent.com/10795207/166519353-79f91bf1-41af-452b-8143-39b41b968492.png">

**Comment by shebinleo** [comment]
This is fixed with the [v2.6.7](https://github.com/shebinleo/pdf2html/releases/tag/v2.6.7) release. Changed the vendor URL to use archive URL to not break in future.

**Comment by chengjianhua** [comment]
@shebinleo Great. Appreciate your great work
