### ISSUE TITLE
Tika app JAR always breaking the packages

### ISSUE THREAD

**Issue by aashari** [shebinleo/pdf2html#37]
We have been seeing a lot of issues related to Tika app JAR (404), can we somehow commit the jar into the repository instead of download it directly from apache.org?

Any thoughts?

**Comment by shebinleo** [comment]
@aashari latest version uses the archive URL for the tika jar which will not break. Which version is breaking for you?

**Comment by aashari** [comment]
Ahhh I see my bad! I just see your latest changes, you update the provider URL to archive URL, thanks mate!
