### ISSUE TITLE
Converted HTML returns blank html

### ISSUE THREAD

**Issue by Ekansh19** [shebinleo/pdf2html#38]
Hi,

After converting the pdf to HTML, am getting the same HTML code against all the files(different) and with almost blank body data.
[jpg2pdf.pdf](https://github.com/shebinleo/pdf2html/files/8785654/jpg2pdf.pdf)

Result HTML:
<img width="570" alt="Screenshot 2022-05-27 at 3 19 38 PM" src="https://user-images.githubusercontent.com/37897001/170675873-a70f0292-95a8-4d02-8bf3-ad4b35a1180d.png">

**Comment by Ekansh19** [comment]
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta name="pdf:PDFVersion" content="1.7"/>
<meta name="pdf:hasXFA" content="false"/>
<meta name="access_permission:modify_annotations" content="true"/>
<meta name="access_permission:can_print_degraded" content="true"/>
<meta name="access_permission:extract_for_accessibility" content="true"/>
<meta name="access_permission:assemble_document" content="true"/>
<meta name="xmpTPg:NPages" content="2"/>
<meta name="resourceName" content="jpg2pdf.pdf"/>
<meta name="pdf:hasXMP" content="false"/>
<meta name="dc:format" content="application/pdf; version=1.7"/>
<meta name="access_permission:extract_content" content="true"/>
<meta name="access_permission:can_print" content="true"/>
<meta name="access_permission:fill_in_form" content="true"/>
<meta name="pdf:hasCollection" content="false"/>
<meta name="X-TIKA:Parsed-By" content="org.apache.tika.parser.DefaultParser"/>
<meta name="X-TIKA:Parsed-By" content="org.apache.tika.parser.pdf.PDFParser"/>
<meta name="pdf:encrypted" content="false"/>
<meta name="Content-Length" content="1247225"/>
<meta name="access_permission:can_modify" content="true"/>
<meta name="pdf:hasMarkedContent" content="false"/>
<meta name="Content-Type" content="application/pdf"/>
<title></title>
</head>
<body><div class="page"><p/>
</div>
<div class="page"><p/>
</div>
</body></html>

**Comment by reregaga** [comment]
This lib cannot get or extract images (like figures or graphs) from pdf,  but you can create an image (thumbnail) from whole page:
```js
const options = { page: 1, imageType: 'png', width: 160, height: 226 }
pdf2html.thumbnail('sample.pdf', options, (err, thumbnailPath) => {
    if (err) {
        console.error('Conversion error: ' + err)
    } else {
        console.log(thumbnailPath)
    }
})
```

For more advanced manipulations use Mozilla's [pdf.js](https://github.com/mozilla/pdf.js)

**Comment by shebinleo** [comment]
Like @reregaga mentioned. this library doesn't extract images. Please feel free to do PR if you would like to add this.
