### ISSUE TITLE
Which version of the java SDK

### ISSUE THREAD

**Issue by tiantianhy** [shebinleo/pdf2html#41]
error: Command failed: java -jar D:\vscodeProject\node\myserve\node_modules\pdf2html\vendor\tika-app-2.4.0.jar --html ../docs/9.5-9.17.pdf
Error: Registry key 'Software\JavaSoft\Java Runtime Environment'\CurrentVersion'
has value '1.8', but '1.7' is required.
Error: could not find java.dll
Error: Could not find Java SE Runtime Environment.

**Comment by shebinleo** [comment]
@tiantianhy That is strange. I was able to run it in 1.8. I tried it on MacOS and will give it a try on windows.

```
java version "1.8.0_331"
Java(TM) SE Runtime Environment (build 1.8.0_331-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.331-b09, mixed mode)
```
