### ISSUE TITLE
Read file from binary (buffer) is missing.

### ISSUE THREAD

**Issue by BartusZak** [shebinleo/pdf2html#7]
I would like to use buffer of a file except url.

eg.

```
const bufferPdf = Buffer.from(pdfToSave.buffer);

      await pdf2html
        .text(pdfBuffer, (err, html) => {
          if (err) {
            console.error("Conversion error: " + err);
          } else {
            console.log(html);
          }
        })
        .promise();
```

**Comment by 61soldiers** [comment]
`pdf2html.text()` converts a pdf to text according to docs.

**Comment by shebinleo** [comment]
Currently, the library uses the external library Tika to generate HTML or text so we cannot use the buffer.  A workaround is to use a file path or save the buffer to a file.
